version: "3"
services:
  api:
    container_name: api
    build:
      context: ./../
      dockerfile: .docker/Dockerfile
      target: dev # use `build` for production
    environment:
        - NODE_ENV=development
        - DB_SERVER=mongodb://mongo/books
        - DB_NAME=books
    ports:
      - "9000:9000"
    volumes:
      - ./../:/app
    links:
      - mongo
  mongo:
    image: mongo:4.4
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: books
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
