version: "3"
services:
  api:
    container_name: api
    build:
      context: ./../
      dockerfile: .docker/Dockerfile
      target: dev # use `prod` for production
    environment:
        - APP_PORT=9000
        - MONGODB_SERVER=mongodb://mongo/books
    ports:
      - "9000:9000"
    volumes:
      - ./../:/usr/src/app
    links:
      - mongo
  mongo:
    image: mongo:4.4
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: books
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
